name: Export Android

on:
  push:
    branches:
      - main
      - master
      - try
  workflow_dispatch:

env:
  GODOT_VERSION: 4.5
  EXPORT_NAME: meaner-matcher
  PROJECT_PATH: .

jobs:
  android_debug:
    name: Android Debug APK
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mkdir -p ~/.config/
          if [ -d /root/.config/godot ]; then mv /root/.config/godot ~/.config/godot; fi
          if [ -d /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ]; then \
            mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable; \
          fi

      - name: Build Android (debug)
        run: |
          mkdir -p build/android
          EXPORT_DIR="$(readlink -f build)"
          cd "$PROJECT_PATH"
          godot --headless --verbose --export-debug "Android Debug" "$EXPORT_DIR/android/${EXPORT_NAME}-debug.apk"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: build/android

